FROM postgres:15

# Configurar las variables de entorno para PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=0000
ENV POSTGRES_DB=proveedores

# Copiar los scripts de inicialización
COPY init.sql /docker-entrypoint-initdb.d/